Task1, Лазарева
ritka-admin/formal-lang-course pull request #1
Opened 2023-02-23 16:57 UTC by ritka-admin

2023-02-23 19:35 UTC, rustam-azimov requested changes

2023-02-23 19:35 UTC, rustam-azimov commented on project/graphs.py
> +def count_vertices(graph: nx.MultiDiGraph):
Для полного соответсвия заданию нужно добавить еще функцию, которая будет вызывать эти три и возвращать named tuple с этой информацией.

2023-02-23 19:35 UTC, rustam-azimov commented on project/graphs.py
> +def make_two_cycled_graph(fst_cycle_vertices, snd_cycle_vertices, labels: tuple):
Также добавить функцию которая будет и создавать и сохранять в файл такой граф.

2023-02-23 19:35 UTC, rustam-azimov commented on tests/test_basic.py
> +    project.graphs.save_graph(graph2, 'lol')
Лучше также иметь правильный вид графа в формате dot и сравнить сохраненный с ним на идентичность.

2023-02-23 21:45 UTC, ritka-admin commented on project/graphs.py
> +def count_vertices(graph: nx.MultiDiGraph):
лектор на вопрос о реализации этих функций ответил, что на каждый запрос (кол-во вершин / рёбер / метки) должна быть своя функция вместо возвращения значений в списке / кортеже. вроде бы в задание не было уточнено это конкретно :(
но хорошо, теперь понятно, исправлю

2023-02-23 22:14 UTC, ritka-admin commented on tests/test_basic.py
> +    project.graphs.save_graph(graph2, 'lol')
а где можно взять правильный вид [графов](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/graphs/index.html) в формате dot для тестов?

2023-02-24 05:42 UTC, rustam-azimov commented on tests/test_basic.py
> +    project.graphs.save_graph(graph2, 'lol')
Либо небольшой граф вручную создать в формате dot и с ним сравнивать файлы, либо можно загрузить и сохранить файл dot для графа из CFPQ_data, потом воспользоваться функцией считыванием обратно в граф и функцией проверки этого графа на равенство с графом, который загружаете с использованием функции из CFPQ_data.

2023-02-26 12:32 UTC, ritka-admin commented on tests/test_basic.py
> +    project.graphs.save_graph(graph2, 'lol')
Спасибо, всё поправила

2023-02-26 18:48 UTC, rustam-azimov approved these changes

2023-03-01 22:07 UTC, merged