HW2, Лазарева Маргарита
ritka-admin/formal-lang-course pull request #2
Opened 2023-03-01 22:09 UTC by ritka-admin

2023-03-02 06:33 UTC, rustam-azimov requested changes

2023-03-02 06:33 UTC, rustam-azimov commented on project/finite_state_automaton.py
> +    deterministic = epsilon_nfa.to_deterministic()
Проверьте документацию библиотеки. Это лишнее

2023-03-02 06:33 UTC, rustam-azimov commented on project/finite_state_automaton.py
> +def regex_to_dfa(raw_regex: str) -> DeterministicFiniteAutomaton:
Теперь к каждой функции пишите пожалуйста документацию

2023-03-02 09:43 UTC, ritka-admin commented on project/finite_state_automaton.py
> +def regex_to_dfa(raw_regex: str) -> DeterministicFiniteAutomaton:
Добавить док стринги к каждой функции Вы имеете в виду? Или достаточно принимаемых и возвращаемых типов?

2023-03-03 08:02 UTC, rustam-azimov commented on project/finite_state_automaton.py
> +def regex_to_dfa(raw_regex: str) -> DeterministicFiniteAutomaton:
Док стринги

2023-03-04 07:55 UTC, rustam-azimov approved these changes

2023-03-18 12:41 UTC, merged