HW6, Лазарева
ritka-admin/formal-lang-course pull request #3
Opened 2023-04-03 17:28 UTC by ritka-admin

В тестах есть закомментированное правило из нетерминала в терминал. Почему-то при приведении грамматики к НФХ это правило выбрасывается, его нет в аттрибуте `productions`. Но этого отличия между ОНФХ и НФХ не указано в `READ.me`. Почему `to_normal_form` выбрасывает продукции вида `B- -> Terminal(b)`?

2023-04-07 13:48 UTC, rustam-azimov commented
> В тестах есть закомментированное правило из нетерминала в терминал. Почему-то при приведении грамматики к НФХ это правило выбрасывается, его нет в аттрибуте `productions`. Но этого отличия между ОНФХ и НФХ не указано в `READ.me`. Почему `to_normal_form` выбрасывает продукции вида `B- -> Terminal(b)`?

Такой вопрос я Вам должен задавать) Ну в нормальной форме выбрасываются недостижимые (useless) правила. То есть из стартового мы никогда к B не придем. Так что правильно что выбрасываются.

2023-04-07 13:51 UTC, rustam-azimov requested changes

2023-04-07 13:51 UTC, rustam-azimov commented on project/cf_grammar.py
> +    epsilon_rules = set(initial_grammar_rules) - set(without_epsilons)  # set of epsilon rules
Собственно на каком то этапе должны были вызвать grammar.eliminate_unit_productions() потом такой метод как remove_useless_symbols(), и методы decompose_productions get_productions_with_only_single_terminals. Посмотрите на эти методы в pyformlang.

2023-04-10 11:35 UTC, ritka-admin commented
> > В тестах есть закомментированное правило из нетерминала в терминал. Почему-то при приведении грамматики к НФХ это правило выбрасывается, его нет в аттрибуте `productions`. Но этого отличия между ОНФХ и НФХ не указано в `READ.me`. Почему `to_normal_form` выбрасывает продукции вида `B- -> Terminal(b)`?
> 
> Такой вопрос я Вам должен задавать) Ну в нормальной форме выбрасываются недостижимые (useless) правила. То есть из стартового мы никогда к B не придем. Так что правильно что выбрасываются.

поняла, спасибо

2023-04-13 10:19 UTC, rustam-azimov approved these changes

2023-04-24 15:22 UTC, merged